<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="table" nsURI="http://table" nsPrefix="table">
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableelements" upperBound="-1"
        eType="#//TableElements" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableElements" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Case" eSuperTypes="#//TableElements">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
        eType="#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" lowerBound="1" eType="#//Line"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" upperBound="-1"
        eType="#//Allocation" eOpposite="#//Allocation/case"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//TableElements">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="case" lowerBound="1" upperBound="-1"
        eType="#//Case" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="INTEGER" literal="integer"/>
    <eLiterals name="FLOAT" value="1" literal="float"/>
    <eLiterals name="STRING" value="2" literal="string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" eSuperTypes="#//TableElements">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="case" lowerBound="1" upperBound="-1"
        eType="#//Case" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stockage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="necessity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="case" lowerBound="1" eType="#//Case"
        eOpposite="#//Case/allocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stockage" lowerBound="1"
        eType="#//Stockage"/>
  </eClassifiers>
</ecore:EPackage>
