/**
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.xtext.shemaTables;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Referenced Column</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getId <em>Id</em>}</li>
 *   <li>{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getDataType <em>Data Type</em>}</li>
 *   <li>{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getConstraint <em>Constraint</em>}</li>
 *   <li>{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getForeignTable <em>Foreign Table</em>}</li>
 *   <li>{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getForeignColumn <em>Foreign Column</em>}</li>
 * </ul>
 *
 * @see fr.n7.idm.project.xtext.shemaTables.ShemaTablesPackage#getReferencedColumn()
 * @model
 * @generated
 */
public interface ReferencedColumn extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.idm.project.xtext.shemaTables.ShemaTablesPackage#getReferencedColumn_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see fr.n7.idm.project.xtext.shemaTables.ShemaTablesPackage#getReferencedColumn_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Data Type</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.idm.project.xtext.shemaTables.ColumnDataType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type</em>' attribute.
   * @see fr.n7.idm.project.xtext.shemaTables.ColumnDataType
   * @see #setDataType(ColumnDataType)
   * @see fr.n7.idm.project.xtext.shemaTables.ShemaTablesPackage#getReferencedColumn_DataType()
   * @model
   * @generated
   */
  ColumnDataType getDataType();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getDataType <em>Data Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Type</em>' attribute.
   * @see fr.n7.idm.project.xtext.shemaTables.ColumnDataType
   * @see #getDataType()
   * @generated
   */
  void setDataType(ColumnDataType value);

  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference.
   * @see #setConstraint(Constraint)
   * @see fr.n7.idm.project.xtext.shemaTables.ShemaTablesPackage#getReferencedColumn_Constraint()
   * @model containment="true"
   * @generated
   */
  Constraint getConstraint();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getConstraint <em>Constraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint</em>' containment reference.
   * @see #getConstraint()
   * @generated
   */
  void setConstraint(Constraint value);

  /**
   * Returns the value of the '<em><b>Foreign Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foreign Table</em>' reference.
   * @see #setForeignTable(ShemaTable)
   * @see fr.n7.idm.project.xtext.shemaTables.ShemaTablesPackage#getReferencedColumn_ForeignTable()
   * @model
   * @generated
   */
  ShemaTable getForeignTable();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getForeignTable <em>Foreign Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Foreign Table</em>' reference.
   * @see #getForeignTable()
   * @generated
   */
  void setForeignTable(ShemaTable value);

  /**
   * Returns the value of the '<em><b>Foreign Column</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foreign Column</em>' reference.
   * @see #setForeignColumn(Column)
   * @see fr.n7.idm.project.xtext.shemaTables.ShemaTablesPackage#getReferencedColumn_ForeignColumn()
   * @model
   * @generated
   */
  Column getForeignColumn();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.xtext.shemaTables.ReferencedColumn#getForeignColumn <em>Foreign Column</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Foreign Column</em>' reference.
   * @see #getForeignColumn()
   * @generated
   */
  void setForeignColumn(Column value);

} // ReferencedColumn
