<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algorithme" nsURI="http://www.example.org/algorithme" nsPrefix="algorithme">
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
        eType="#//Resource" eOpposite="#//Resource/resourceAlgos"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//Input"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//Output" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileOfAlgo" lowerBound="1"
        eType="#//AlgorithmFile" eOpposite="#//AlgorithmFile/algoOfFile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folderPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceAlgos" upperBound="-1"
        eType="#//Algorithm" eOpposite="#//Algorithm/resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ressourceFiles" upperBound="-1"
        eType="#//AlgorithmFile" eOpposite="#//AlgorithmFile/fileResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algoOfFile" lowerBound="1"
        eType="#//Algorithm" eOpposite="#//Algorithm/fileOfAlgo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileResource" lowerBound="1"
        eType="#//Resource" eOpposite="#//Resource/ressourceFiles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputColumn" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../fr.n7.idm.project.shematable/model/shematable.ecore#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constante" eType="#//Constant"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputColumn" lowerBound="1"
        eType="ecore:EClass ../../fr.n7.idm.project.shematable/model/shematable.ecore#//DerivedColumn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cons" eType="ecore:EEnum ../../fr.n7.idm.project.shematable/model/shematable.ecore#//ColumnDataType"/>
  </eClassifiers>
</ecore:EPackage>
