/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.shemaTables.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractXtextValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.n7.idm.project.shemaTables.xtext.XtextPackage.eINSTANCE);
		return result;
	}
}
