/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.xtext.parser.antlr;

import com.google.inject.Inject;
import fr.n7.idm.project.xtext.parser.antlr.internal.InternalShemaTablesParser;
import fr.n7.idm.project.xtext.services.ShemaTablesGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ShemaTablesParser extends AbstractAntlrParser {

	@Inject
	private ShemaTablesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalShemaTablesParser createParser(XtextTokenStream stream) {
		return new InternalShemaTablesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Tables";
	}

	public ShemaTablesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ShemaTablesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
