/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.shemaTables.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XtextUiModule extends AbstractXtextUiModule {

	public XtextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
