/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.shemaTables.parser.antlr;

import com.google.inject.Inject;
import fr.n7.idm.project.shemaTables.parser.antlr.internal.InternalXtextParser;
import fr.n7.idm.project.shemaTables.services.XtextGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XtextParser extends AbstractAntlrParser {

	@Inject
	private XtextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXtextParser createParser(XtextTokenStream stream) {
		return new InternalXtextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Tables";
	}

	public XtextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XtextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
