<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algorithme" nsURI="http://algorithme" nsPrefix="algorithme">
  <eClassifiers xsi:type="ecore:EClass" name="Algorithme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algoelements" upperBound="-1"
        eType="#//AlgoElements" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgoElements" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Input" abstract="true" eSuperTypes="#//AlgoElements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
        upperBound="-1" eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" lowerBound="1"
        upperBound="-1" eType="#//Operator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//AlgoElements"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//OperatorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorType">
    <eLiterals name="SOMME" literal="SOMME"/>
    <eLiterals name="SOUSTRACTION" value="1" literal="SOUSTRACTION"/>
    <eLiterals name="PRODUIT" value="2"/>
    <eLiterals name="RAPPORT" value="3"/>
    <eLiterals name="SIN" value="4"/>
    <eLiterals name="COS" value="5"/>
    <eLiterals name="TAN" value="6"/>
    <eLiterals name="MIN" value="7"/>
    <eLiterals name="MAX" value="8"/>
    <eLiterals name="AVG" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parametre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableSourceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id_column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hérite de column"/>
  </eClassifiers>
</ecore:EPackage>
