/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.shemaTables.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.n7.idm.project.shemaTables.XtextRuntimeModule;
import fr.n7.idm.project.shemaTables.XtextStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class XtextIdeSetup extends XtextStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new XtextRuntimeModule(), new XtextIdeModule()));
	}
	
}
