<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="shematable" nsURI="http://www.example.org/shematable" nsPrefix="shematable">
  <eClassifiers xsi:type="ecore:EClass" name="ShemaTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="#//ColumnDataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintFile" lowerBound="1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedColumn" eSuperTypes="#//Column">
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignTable" lowerBound="1"
        eType="#//ShemaTable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignColumn" lowerBound="1"
        eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedColumn" eSuperTypes="#//Column"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ColumnDataType">
    <eLiterals name="int"/>
    <eLiterals name="float" value="1"/>
    <eLiterals name="string" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
