/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.shemaTables.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class XtextProposalProvider extends AbstractXtextProposalProvider {
}
