/**
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.shemaTables.xtext;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Derived Column</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getId <em>Id</em>}</li>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getDataType <em>Data Type</em>}</li>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getConstraint <em>Constraint</em>}</li>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getAlgorithm <em>Algorithm</em>}</li>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getOutputColumn <em>Output Column</em>}</li>
 * </ul>
 *
 * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getDerivedColumn()
 * @model
 * @generated
 */
public interface DerivedColumn extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getDerivedColumn_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getDerivedColumn_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Data Type</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.idm.project.shemaTables.xtext.ColumnDataType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type</em>' attribute.
   * @see fr.n7.idm.project.shemaTables.xtext.ColumnDataType
   * @see #setDataType(ColumnDataType)
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getDerivedColumn_DataType()
   * @model
   * @generated
   */
  ColumnDataType getDataType();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getDataType <em>Data Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Type</em>' attribute.
   * @see fr.n7.idm.project.shemaTables.xtext.ColumnDataType
   * @see #getDataType()
   * @generated
   */
  void setDataType(ColumnDataType value);

  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference.
   * @see #setConstraint(Constraint)
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getDerivedColumn_Constraint()
   * @model containment="true"
   * @generated
   */
  Constraint getConstraint();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getConstraint <em>Constraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint</em>' containment reference.
   * @see #getConstraint()
   * @generated
   */
  void setConstraint(Constraint value);

  /**
   * Returns the value of the '<em><b>Algorithm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algorithm</em>' containment reference.
   * @see #setAlgorithm(Algorithm)
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getDerivedColumn_Algorithm()
   * @model containment="true"
   * @generated
   */
  Algorithm getAlgorithm();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getAlgorithm <em>Algorithm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algorithm</em>' containment reference.
   * @see #getAlgorithm()
   * @generated
   */
  void setAlgorithm(Algorithm value);

  /**
   * Returns the value of the '<em><b>Output Column</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output Column</em>' containment reference.
   * @see #setOutputColumn(Output)
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getDerivedColumn_OutputColumn()
   * @model containment="true"
   * @generated
   */
  Output getOutputColumn();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getOutputColumn <em>Output Column</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output Column</em>' containment reference.
   * @see #getOutputColumn()
   * @generated
   */
  void setOutputColumn(Output value);

} // DerivedColumn
