/**
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.shemaTables.xtext;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shema Table</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getId <em>Id</em>}</li>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getColumns <em>Columns</em>}</li>
 *   <li>{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getCatalogue <em>Catalogue</em>}</li>
 * </ul>
 *
 * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getShemaTable()
 * @model
 * @generated
 */
public interface ShemaTable extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getShemaTable_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getShemaTable_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Columns</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.idm.project.shemaTables.xtext.Column}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' containment reference list.
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getShemaTable_Columns()
   * @model containment="true"
   * @generated
   */
  EList<Column> getColumns();

  /**
   * Returns the value of the '<em><b>Catalogue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Catalogue</em>' containment reference.
   * @see #setCatalogue(Catalogue)
   * @see fr.n7.idm.project.shemaTables.xtext.XtextPackage#getShemaTable_Catalogue()
   * @model containment="true"
   * @generated
   */
  Catalogue getCatalogue();

  /**
   * Sets the value of the '{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getCatalogue <em>Catalogue</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Catalogue</em>' containment reference.
   * @see #getCatalogue()
   * @generated
   */
  void setCatalogue(Catalogue value);

} // ShemaTable
