/**
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.shemaTables.xtext;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.idm.project.shemaTables.xtext.XtextFactory
 * @model kind="package"
 * @generated
 */
public interface XtextPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xtext";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/idm/project/shemaTables/Xtext";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xtext";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XtextPackage eINSTANCE = fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.TablesImpl <em>Tables</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.TablesImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getTables()
   * @generated
   */
  int TABLES = 0;

  /**
   * The feature id for the '<em><b>Shematables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLES__SHEMATABLES = 0;

  /**
   * The number of structural features of the '<em>Tables</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ShemaTableImpl <em>Shema Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.ShemaTableImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getShemaTable()
   * @generated
   */
  int SHEMA_TABLE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHEMA_TABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHEMA_TABLE__ID = 1;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHEMA_TABLE__COLUMNS = 2;

  /**
   * The feature id for the '<em><b>Catalogue</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHEMA_TABLE__CATALOGUE = 3;

  /**
   * The number of structural features of the '<em>Shema Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHEMA_TABLE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ColumnImpl <em>Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.ColumnImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getColumn()
   * @generated
   */
  int COLUMN = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__ID = 1;

  /**
   * The feature id for the '<em><b>Data Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__DATA_TYPE = 2;

  /**
   * The feature id for the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__CONSTRAINT = 3;

  /**
   * The number of structural features of the '<em>Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ReferencedColumnImpl <em>Referenced Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.ReferencedColumnImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getReferencedColumn()
   * @generated
   */
  int REFERENCED_COLUMN = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCED_COLUMN__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCED_COLUMN__ID = 1;

  /**
   * The feature id for the '<em><b>Data Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCED_COLUMN__DATA_TYPE = 2;

  /**
   * The feature id for the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCED_COLUMN__CONSTRAINT = 3;

  /**
   * The feature id for the '<em><b>Foreign Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCED_COLUMN__FOREIGN_TABLE = 4;

  /**
   * The feature id for the '<em><b>Foreign Column</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCED_COLUMN__FOREIGN_COLUMN = 5;

  /**
   * The number of structural features of the '<em>Referenced Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCED_COLUMN_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.DerivedColumnImpl <em>Derived Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.DerivedColumnImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getDerivedColumn()
   * @generated
   */
  int DERIVED_COLUMN = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DERIVED_COLUMN__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DERIVED_COLUMN__ID = 1;

  /**
   * The feature id for the '<em><b>Data Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DERIVED_COLUMN__DATA_TYPE = 2;

  /**
   * The feature id for the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DERIVED_COLUMN__CONSTRAINT = 3;

  /**
   * The feature id for the '<em><b>Algorithm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DERIVED_COLUMN__ALGORITHM = 4;

  /**
   * The feature id for the '<em><b>Output Column</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DERIVED_COLUMN__OUTPUT_COLUMN = 5;

  /**
   * The number of structural features of the '<em>Derived Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DERIVED_COLUMN_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.ConstraintImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 5;

  /**
   * The feature id for the '<em><b>File Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__FILE_PATH = 0;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.CatalogueImpl <em>Catalogue</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.CatalogueImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getCatalogue()
   * @generated
   */
  int CATALOGUE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATALOGUE__NAME = 0;

  /**
   * The feature id for the '<em><b>Algorithms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATALOGUE__ALGORITHMS = 1;

  /**
   * The number of structural features of the '<em>Catalogue</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATALOGUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.AlgorithmImpl <em>Algorithm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.AlgorithmImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getAlgorithm()
   * @generated
   */
  int ALGORITHM = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__NAME = 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__PATH = 1;

  /**
   * The feature id for the '<em><b>Output</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__OUTPUT = 2;

  /**
   * The feature id for the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__INPUT = 3;

  /**
   * The number of structural features of the '<em>Algorithm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.InputImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getInput()
   * @generated
   */
  int INPUT = 8;

  /**
   * The feature id for the '<em><b>Constante</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__CONSTANTE = 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__COLUMNS = 1;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.OutputImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__ID = 1;

  /**
   * The feature id for the '<em><b>Data Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__DATA_TYPE = 2;

  /**
   * The feature id for the '<em><b>Constraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__CONSTRAINT = 3;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ConstantImpl <em>Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.impl.ConstantImpl
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getConstant()
   * @generated
   */
  int CONSTANT = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.n7.idm.project.shemaTables.xtext.ColumnDataType <em>Column Data Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.idm.project.shemaTables.xtext.ColumnDataType
   * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getColumnDataType()
   * @generated
   */
  int COLUMN_DATA_TYPE = 11;


  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.Tables <em>Tables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tables</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Tables
   * @generated
   */
  EClass getTables();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.idm.project.shemaTables.xtext.Tables#getShematables <em>Shematables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Shematables</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Tables#getShematables()
   * @see #getTables()
   * @generated
   */
  EReference getTables_Shematables();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable <em>Shema Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shema Table</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ShemaTable
   * @generated
   */
  EClass getShemaTable();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ShemaTable#getName()
   * @see #getShemaTable()
   * @generated
   */
  EAttribute getShemaTable_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ShemaTable#getId()
   * @see #getShemaTable()
   * @generated
   */
  EAttribute getShemaTable_Id();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ShemaTable#getColumns()
   * @see #getShemaTable()
   * @generated
   */
  EReference getShemaTable_Columns();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.ShemaTable#getCatalogue <em>Catalogue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Catalogue</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ShemaTable#getCatalogue()
   * @see #getShemaTable()
   * @generated
   */
  EReference getShemaTable_Catalogue();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.Column <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Column
   * @generated
   */
  EClass getColumn();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Column#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Column#getName()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Column#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Column#getId()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_Id();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Column#getDataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data Type</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Column#getDataType()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_DataType();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.Column#getConstraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constraint</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Column#getConstraint()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_Constraint();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.ReferencedColumn <em>Referenced Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Referenced Column</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ReferencedColumn
   * @generated
   */
  EClass getReferencedColumn();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getName()
   * @see #getReferencedColumn()
   * @generated
   */
  EAttribute getReferencedColumn_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getId()
   * @see #getReferencedColumn()
   * @generated
   */
  EAttribute getReferencedColumn_Id();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getDataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data Type</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getDataType()
   * @see #getReferencedColumn()
   * @generated
   */
  EAttribute getReferencedColumn_DataType();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getConstraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constraint</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getConstraint()
   * @see #getReferencedColumn()
   * @generated
   */
  EReference getReferencedColumn_Constraint();

  /**
   * Returns the meta object for the reference '{@link fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getForeignTable <em>Foreign Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Foreign Table</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getForeignTable()
   * @see #getReferencedColumn()
   * @generated
   */
  EReference getReferencedColumn_ForeignTable();

  /**
   * Returns the meta object for the reference '{@link fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getForeignColumn <em>Foreign Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Foreign Column</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ReferencedColumn#getForeignColumn()
   * @see #getReferencedColumn()
   * @generated
   */
  EReference getReferencedColumn_ForeignColumn();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn <em>Derived Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Derived Column</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.DerivedColumn
   * @generated
   */
  EClass getDerivedColumn();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getName()
   * @see #getDerivedColumn()
   * @generated
   */
  EAttribute getDerivedColumn_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getId()
   * @see #getDerivedColumn()
   * @generated
   */
  EAttribute getDerivedColumn_Id();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getDataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data Type</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getDataType()
   * @see #getDerivedColumn()
   * @generated
   */
  EAttribute getDerivedColumn_DataType();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getConstraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constraint</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getConstraint()
   * @see #getDerivedColumn()
   * @generated
   */
  EReference getDerivedColumn_Constraint();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getAlgorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Algorithm</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getAlgorithm()
   * @see #getDerivedColumn()
   * @generated
   */
  EReference getDerivedColumn_Algorithm();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getOutputColumn <em>Output Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Output Column</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.DerivedColumn#getOutputColumn()
   * @see #getDerivedColumn()
   * @generated
   */
  EReference getDerivedColumn_OutputColumn();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Constraint#getFilePath <em>File Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File Path</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Constraint#getFilePath()
   * @see #getConstraint()
   * @generated
   */
  EAttribute getConstraint_FilePath();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.Catalogue <em>Catalogue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Catalogue</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Catalogue
   * @generated
   */
  EClass getCatalogue();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Catalogue#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Catalogue#getName()
   * @see #getCatalogue()
   * @generated
   */
  EAttribute getCatalogue_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.idm.project.shemaTables.xtext.Catalogue#getAlgorithms <em>Algorithms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Algorithms</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Catalogue#getAlgorithms()
   * @see #getCatalogue()
   * @generated
   */
  EReference getCatalogue_Algorithms();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.Algorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithm</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Algorithm
   * @generated
   */
  EClass getAlgorithm();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Algorithm#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Algorithm#getName()
   * @see #getAlgorithm()
   * @generated
   */
  EAttribute getAlgorithm_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Algorithm#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Algorithm#getPath()
   * @see #getAlgorithm()
   * @generated
   */
  EAttribute getAlgorithm_Path();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.Algorithm#getOutput <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Output</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Algorithm#getOutput()
   * @see #getAlgorithm()
   * @generated
   */
  EReference getAlgorithm_Output();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.Algorithm#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Input</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Algorithm#getInput()
   * @see #getAlgorithm()
   * @generated
   */
  EReference getAlgorithm_Input();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.Input#getConstante <em>Constante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constante</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Input#getConstante()
   * @see #getInput()
   * @generated
   */
  EReference getInput_Constante();

  /**
   * Returns the meta object for the reference list '{@link fr.n7.idm.project.shemaTables.xtext.Input#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Columns</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Input#getColumns()
   * @see #getInput()
   * @generated
   */
  EReference getInput_Columns();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Output#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Output#getName()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Output#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Output#getId()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Id();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Output#getDataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data Type</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Output#getDataType()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_DataType();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.idm.project.shemaTables.xtext.Output#getConstraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constraint</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Output#getConstraint()
   * @see #getOutput()
   * @generated
   */
  EReference getOutput_Constraint();

  /**
   * Returns the meta object for class '{@link fr.n7.idm.project.shemaTables.xtext.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constant</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Constant
   * @generated
   */
  EClass getConstant();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.idm.project.shemaTables.xtext.Constant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.Constant#getValue()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_Value();

  /**
   * Returns the meta object for enum '{@link fr.n7.idm.project.shemaTables.xtext.ColumnDataType <em>Column Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Column Data Type</em>'.
   * @see fr.n7.idm.project.shemaTables.xtext.ColumnDataType
   * @generated
   */
  EEnum getColumnDataType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XtextFactory getXtextFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.TablesImpl <em>Tables</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.TablesImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getTables()
     * @generated
     */
    EClass TABLES = eINSTANCE.getTables();

    /**
     * The meta object literal for the '<em><b>Shematables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLES__SHEMATABLES = eINSTANCE.getTables_Shematables();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ShemaTableImpl <em>Shema Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.ShemaTableImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getShemaTable()
     * @generated
     */
    EClass SHEMA_TABLE = eINSTANCE.getShemaTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHEMA_TABLE__NAME = eINSTANCE.getShemaTable_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHEMA_TABLE__ID = eINSTANCE.getShemaTable_Id();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHEMA_TABLE__COLUMNS = eINSTANCE.getShemaTable_Columns();

    /**
     * The meta object literal for the '<em><b>Catalogue</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHEMA_TABLE__CATALOGUE = eINSTANCE.getShemaTable_Catalogue();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ColumnImpl <em>Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.ColumnImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getColumn()
     * @generated
     */
    EClass COLUMN = eINSTANCE.getColumn();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__NAME = eINSTANCE.getColumn_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__ID = eINSTANCE.getColumn_Id();

    /**
     * The meta object literal for the '<em><b>Data Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__DATA_TYPE = eINSTANCE.getColumn_DataType();

    /**
     * The meta object literal for the '<em><b>Constraint</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__CONSTRAINT = eINSTANCE.getColumn_Constraint();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ReferencedColumnImpl <em>Referenced Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.ReferencedColumnImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getReferencedColumn()
     * @generated
     */
    EClass REFERENCED_COLUMN = eINSTANCE.getReferencedColumn();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCED_COLUMN__NAME = eINSTANCE.getReferencedColumn_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCED_COLUMN__ID = eINSTANCE.getReferencedColumn_Id();

    /**
     * The meta object literal for the '<em><b>Data Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCED_COLUMN__DATA_TYPE = eINSTANCE.getReferencedColumn_DataType();

    /**
     * The meta object literal for the '<em><b>Constraint</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCED_COLUMN__CONSTRAINT = eINSTANCE.getReferencedColumn_Constraint();

    /**
     * The meta object literal for the '<em><b>Foreign Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCED_COLUMN__FOREIGN_TABLE = eINSTANCE.getReferencedColumn_ForeignTable();

    /**
     * The meta object literal for the '<em><b>Foreign Column</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCED_COLUMN__FOREIGN_COLUMN = eINSTANCE.getReferencedColumn_ForeignColumn();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.DerivedColumnImpl <em>Derived Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.DerivedColumnImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getDerivedColumn()
     * @generated
     */
    EClass DERIVED_COLUMN = eINSTANCE.getDerivedColumn();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DERIVED_COLUMN__NAME = eINSTANCE.getDerivedColumn_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DERIVED_COLUMN__ID = eINSTANCE.getDerivedColumn_Id();

    /**
     * The meta object literal for the '<em><b>Data Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DERIVED_COLUMN__DATA_TYPE = eINSTANCE.getDerivedColumn_DataType();

    /**
     * The meta object literal for the '<em><b>Constraint</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DERIVED_COLUMN__CONSTRAINT = eINSTANCE.getDerivedColumn_Constraint();

    /**
     * The meta object literal for the '<em><b>Algorithm</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DERIVED_COLUMN__ALGORITHM = eINSTANCE.getDerivedColumn_Algorithm();

    /**
     * The meta object literal for the '<em><b>Output Column</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DERIVED_COLUMN__OUTPUT_COLUMN = eINSTANCE.getDerivedColumn_OutputColumn();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.ConstraintImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '<em><b>File Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTRAINT__FILE_PATH = eINSTANCE.getConstraint_FilePath();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.CatalogueImpl <em>Catalogue</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.CatalogueImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getCatalogue()
     * @generated
     */
    EClass CATALOGUE = eINSTANCE.getCatalogue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CATALOGUE__NAME = eINSTANCE.getCatalogue_Name();

    /**
     * The meta object literal for the '<em><b>Algorithms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CATALOGUE__ALGORITHMS = eINSTANCE.getCatalogue_Algorithms();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.AlgorithmImpl <em>Algorithm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.AlgorithmImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getAlgorithm()
     * @generated
     */
    EClass ALGORITHM = eINSTANCE.getAlgorithm();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM__NAME = eINSTANCE.getAlgorithm_Name();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM__PATH = eINSTANCE.getAlgorithm_Path();

    /**
     * The meta object literal for the '<em><b>Output</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHM__OUTPUT = eINSTANCE.getAlgorithm_Output();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHM__INPUT = eINSTANCE.getAlgorithm_Input();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.InputImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>Constante</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT__CONSTANTE = eINSTANCE.getInput_Constante();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT__COLUMNS = eINSTANCE.getInput_Columns();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.OutputImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__NAME = eINSTANCE.getOutput_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__ID = eINSTANCE.getOutput_Id();

    /**
     * The meta object literal for the '<em><b>Data Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__DATA_TYPE = eINSTANCE.getOutput_DataType();

    /**
     * The meta object literal for the '<em><b>Constraint</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTPUT__CONSTRAINT = eINSTANCE.getOutput_Constraint();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.impl.ConstantImpl <em>Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.impl.ConstantImpl
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getConstant()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__VALUE = eINSTANCE.getConstant_Value();

    /**
     * The meta object literal for the '{@link fr.n7.idm.project.shemaTables.xtext.ColumnDataType <em>Column Data Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.idm.project.shemaTables.xtext.ColumnDataType
     * @see fr.n7.idm.project.shemaTables.xtext.impl.XtextPackageImpl#getColumnDataType()
     * @generated
     */
    EEnum COLUMN_DATA_TYPE = eINSTANCE.getColumnDataType();

  }

} //XtextPackage
