/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractShemaTablesScopeProvider extends DelegatingScopeProvider {
}
