/*
 * generated by Xtext 2.32.0
 */
package fr.n7.idm.project.shemaTables;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class XtextStandaloneSetup extends XtextStandaloneSetupGenerated {

	public static void doSetup() {
		new XtextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
